import Link from "next/link";
import { BarChart3, CalendarClock, CheckCircle2, LayoutList, Menu, ShieldCheck, BadgeCheck, Ban, Building2, Rocket, Users, X } from "lucide-react";
const links = [
  { href: "/dashboard", label: "Dashboard", icon: BarChart3 }, { href: "/demands", label: "Demandas", icon: LayoutList }, { href: "/approvals", label: "Pendentes de análise", icon: ShieldCheck }, { href: "/rejected", label: "Demandas reprovadas", icon: Ban }, { href: "/confirmations", label: "Pendentes de confirmação", icon: BadgeCheck }, { href: "/post-go-live", label: "Demandas pós-go-live", icon: CalendarClock }, { href: "/future-versions", label: "Próximas versões", icon: Rocket }, { href: "/team", label: "Membros da equipe", icon: Users },
  { href: "/demands?completed=true", label: "Concluídos", icon: CheckCircle2 },
];
export function AppShell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen lg:grid lg:grid-cols-[248px_1fr]">
    <input id="nav" type="checkbox" className="peer hidden" />
    <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-indigo-100 bg-indigo-50/90 px-4 backdrop-blur lg:hidden"><Link href="/dashboard" className="font-serif text-xl font-bold tracking-tight text-indigo-950"><span className="mr-1 font-mono text-sm text-cyan-600">~/</span>Zé-landia</Link><label htmlFor="nav" className="focus-ring rounded p-2"><Menu className="size-5" /></label></header>
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-[248px] flex-col border-r border-indigo-400/20 bg-[linear-gradient(165deg,#11152f_0%,#17153b_55%,#10182f_100%)] text-slate-200 shadow-2xl shadow-indigo-950/20 peer-checked:flex lg:sticky lg:top-0 lg:flex lg:h-screen">
      <div className="relative flex min-h-28 items-center justify-between overflow-hidden border-b border-white/10 px-6 py-4 before:absolute before:-right-8 before:-top-10 before:size-28 before:rounded-full before:bg-cyan-400/10 before:blur-2xl"><Link href="/dashboard" className="relative"><span className="block font-serif text-2xl font-bold tracking-tight text-white"><span className="mr-1 font-mono text-sm font-medium text-cyan-300">~/</span>Zé-landia<span className="ml-1 text-violet-400">_</span></span><span className="mt-1.5 block font-mono text-[10px] font-medium uppercase leading-4 tracking-[.1em] text-indigo-200">Backlog e Prioridades<br/>do Site 2026</span><span className="mt-2 block font-mono text-[10px] italic tracking-wide text-cyan-300/80"><span className="text-violet-400">$</span> 4 devs e um sonho</span></Link><label htmlFor="nav" className="lg:hidden"><X className="size-5" /></label></div>
      <nav className="flex-1 space-y-1.5 p-3">{links.map(({ href, label, icon: Icon }) => <Link key={label} href={href} className="focus-ring group flex items-center gap-3 rounded-lg border border-transparent px-3 py-2.5 text-sm transition hover:border-cyan-300/10 hover:bg-gradient-to-r hover:from-cyan-400/10 hover:to-violet-400/10 hover:text-white"><Icon className="size-4 text-indigo-300 transition group-hover:text-cyan-300" />{label}</Link>)}</nav>
      <div className="border-t border-white/10 px-5 py-5"><div className="flex items-start gap-3 rounded-lg border border-violet-300/10 bg-violet-400/5 p-3"><span className="mt-0.5 rounded-md bg-cyan-400/10 p-2 text-cyan-300"><Building2 className="size-4"/></span><div><p className="font-mono text-[11px] font-semibold uppercase tracking-[.1em] text-indigo-200">Painel Comercial</p><p className="mt-1 text-[11px] leading-4 text-slate-400">Uso exclusivo para desenvolvimento de demandas do novo site.</p></div></div></div>
    </aside>
    <main className="min-w-0">{children}</main>
  </div>;
}
