"use client";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { SubmitButton } from "./submit-button";
import { MultipleImageFields } from "./multiple-image-fields";
type Category = { id: string; name: string };
const developers = ["Vitor Moraes", "Lauro", "José", "Marco", "Elvis", "Wanderson"];
const control = "focus-ring mt-1.5 w-full rounded-md border bg-white px-3 py-2.5 text-sm";
export function NewDemandForm({ categories, action }: { categories: Category[]; action: (formData: FormData) => void | Promise<void> }) { const [items,setItems] = useState([crypto.randomUUID()]); return <form action={action} className="mx-auto max-w-5xl space-y-6"><section className="panel rounded-lg p-5 sm:p-7"><h2 className="mb-5 text-lg font-semibold">Informações gerais</h2><div className="grid gap-5 sm:grid-cols-2"><Field label="Título" name="title" required className="sm:col-span-2"/><Select label="Categoria" name="category_id" options={categories.map((category) => ({value:category.id,label:category.name}))}/><Select label="Responsável geral" name="developer" options={developers.map((name) => ({value:name,label:name}))}/><Select label="Prioridade" name="priority" options={["Alta","Média","Baixa"].map((value) => ({value,label:value}))}/><Field label="Prazo" name="deadline" type="date"/></div><p className="mt-5 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">A demanda será criada como <strong>Pendente de aprovação</strong> e não aparecerá na listagem principal até ser aprovada.</p></section><section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Itens</h2><button type="button" onClick={() => setItems((current) => [...current, crypto.randomUUID()])} className="flex items-center gap-2 rounded-md border bg-white px-3 py-2 text-sm font-semibold"><Plus className="size-4"/>Adicionar item</button></div><div className="space-y-4">{items.map((key,index) => <div key={key} className="panel rounded-lg p-5 sm:p-7"><input type="hidden" name="item_key" value={key}/><div className="mb-4 flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">Item {index+1}</p>{items.length > 1 && <button type="button" onClick={() => setItems((current) => current.filter((item) => item !== key))} className="text-red-600"><Trash2 className="size-4"/></button>}</div><div className="grid gap-5 sm:grid-cols-2"><Select label="Tipo" name="item_type" options={[{value:"change",label:"Ajuste"},{value:"question",label:"Dúvida"},{value:"reference",label:"Referência"},{value:"figma",label:"Figma"},{value:"other",label:"Outro"}]}/><Select label="Atribuir a" name="item_assignee" options={developers.map((name) => ({value:name,label:name}))}/><label className="sm:col-span-2"><span className="text-sm font-medium text-slate-700">Descrição</span><textarea name="item_description" required className={`${control} min-h-28 resize-y`}/></label><MultipleImageFields prefix={`item_image_${key}`}/></div></div>)}</div></section><div className="flex justify-end border-t py-4"><SubmitButton/></div></form>; }
function Field({label,name,type="text",required,className=""}:{label:string;name:string;type?:string;required?:boolean;className?:string}) { return <label className={className}><span className="text-sm font-medium text-slate-700">{label}</span><input name={name} type={type} required={required} className={control}/></label>; }
function Select({label,name,options}:{label:string;name:string;options:{value:string;label:string}[]}) { return <label><span className="text-sm font-medium text-slate-700">{label}</span><select name={name} className={control}><option value="">Não definido</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
