import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays, Pencil, UserRound } from "lucide-react";
import { getDemand, signDemandImages } from "@/lib/data/demands";
import { PriorityBadge, StatusBadge } from "@/components/badges";
import { DemandItem } from "@/components/demand-item";
export default async function DemandDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const found = await getDemand(id); if (!found) notFound(); const demand = await signDemandImages(found); return <><header className="border-b bg-white px-5 py-6 sm:px-8 lg:px-10"><Link href="/demands" className="mb-5 inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-slate-950"><ArrowLeft className="size-4"/>Voltar para demandas</Link><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><div className="mb-2 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="font-medium text-blue-700">{demand.category?.name ?? "Sem categoria"}</span>{demand.sourceId && <span>#{demand.sourceId}</span>}</div><h1 className="max-w-4xl text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{demand.title}</h1><div className="mt-4 flex flex-wrap gap-2"><PriorityBadge value={demand.priority}/><StatusBadge value={demand.status}/></div></div><Link href={`/demands/${id}/edit`} className="focus-ring flex w-fit items-center gap-2 rounded-md border bg-white px-4 py-2.5 text-sm font-semibold hover:bg-slate-50"><Pencil className="size-4"/>Editar demanda</Link></div><dl className="mt-7 grid gap-4 border-t pt-5 sm:grid-cols-2 xl:grid-cols-4"><Meta label="Responsável" value={demand.developer} icon={<UserRound className="size-4"/>}/><Meta label="Prazo" value={formatDate(demand.deadline)} icon={<CalendarDays className="size-4"/>}/><Meta label="Resultado da validação" value={demand.validationResult}/><Meta label="Observações" value={demand.validationNotes}/></dl></header><main className="p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-6xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-950">Itens da demanda</h2><span className="text-sm text-slate-500">{demand.items.length} itens</span></div><div className="space-y-4">{demand.items.length ? demand.items.map((item) => <DemandItem key={item.id} item={item}/>) : <div className="panel rounded-lg p-10 text-center text-sm text-slate-500">Esta demanda ainda não possui itens.</div>}</div></div></main></>; }
function Meta({label,value,icon}:{label:string;value?:string;icon?:React.ReactNode}) { return <div><dt className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">{icon}{label}</dt><dd className="mt-1.5 text-sm font-medium text-slate-700">{value || "—"}</dd></div>; }
function formatDate(value?: string) { if (!value) return undefined; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat("pt-BR").format(date); }
