export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type Rel<Name extends string, Columns extends string[], Ref extends string> = { foreignKeyName: Name; columns: Columns; isOneToOne: false; referencedRelation: Ref; referencedColumns: ["id"] };
type Table<Row, Insert, Update, Relationships extends readonly object[] = []> = { Row: Row; Insert: Insert; Update: Update; Relationships: Relationships };
export type Database = { __InternalSupabase: { PostgrestVersion: "14.17" }; public: { Tables: {
  adjustment_categories: Table<{ created_at: string; id: string; name: string; slug: string; source_numeric_id: number | null; updated_at: string }, { created_at?: string; id?: string; name: string; slug: string; source_numeric_id?: number | null; updated_at?: string }, { created_at?: string; id?: string; name?: string; slug?: string; source_numeric_id?: number | null; updated_at?: string }>;
  adjustment_demands: Table<{ category_id: string | null; created_at: string; deadline: string | null; developer: string | null; developer_response_general: string | null; heading_raw: string | null; id: string; priority: string | null; source_id: string | null; source_key: string; source_order: number; status: string | null; title: string; updated_at: string; validation_notes: string | null; validation_result: string | null }, { category_id?: string | null; created_at?: string; deadline?: string | null; developer?: string | null; developer_response_general?: string | null; heading_raw?: string | null; id?: string; priority?: string | null; source_id?: string | null; source_key: string; source_order: number; status?: string | null; title: string; updated_at?: string; validation_notes?: string | null; validation_result?: string | null }, { category_id?: string | null; created_at?: string; deadline?: string | null; developer?: string | null; developer_response_general?: string | null; heading_raw?: string | null; id?: string; priority?: string | null; source_id?: string | null; source_key?: string; source_order?: number; status?: string | null; title?: string; updated_at?: string; validation_notes?: string | null; validation_result?: string | null }, [Rel<"adjustment_demands_category_id_fkey", ["category_id"], "adjustment_categories">]>;
  adjustment_items: Table<{ created_at: string; demand_id: string; description: string | null; description_rich: Json; developer_response: string | null; id: string; item_type: string; semantics: Json; sort_order: number; source_item_label: string | null; source_item_number: number | null; source_key: string; type_raw: string | null; updated_at: string }, { created_at?: string; demand_id: string; description?: string | null; description_rich?: Json; developer_response?: string | null; id?: string; item_type: string; semantics?: Json; sort_order?: number; source_item_label?: string | null; source_item_number?: number | null; source_key: string; type_raw?: string | null; updated_at?: string }, { created_at?: string; demand_id?: string; description?: string | null; description_rich?: Json; developer_response?: string | null; id?: string; item_type?: string; semantics?: Json; sort_order?: number; source_item_label?: string | null; source_item_number?: number | null; source_key?: string; type_raw?: string | null; updated_at?: string }, [Rel<"adjustment_items_demand_id_fkey", ["demand_id"], "adjustment_demands">]>;
  adjustment_attachments: Table<{ created_at: string; filename: string; height: number | null; id: string; mime_type: string | null; sha256: string | null; size_bytes: number | null; source_media: string; storage_bucket: string; storage_path: string; width: number | null }, { created_at?: string; filename: string; height?: number | null; id?: string; mime_type?: string | null; sha256?: string | null; size_bytes?: number | null; source_media: string; storage_bucket?: string; storage_path: string; width?: number | null }, { created_at?: string; filename?: string; height?: number | null; id?: string; mime_type?: string | null; sha256?: string | null; size_bytes?: number | null; source_media?: string; storage_bucket?: string; storage_path?: string; width?: number | null }>;
  adjustment_item_attachments: Table<{ attachment_id: string; created_at: string; demand_id: string; id: string; item_id: string | null; reference_label: string | null; role: string; shared_reference: boolean }, { attachment_id: string; created_at?: string; demand_id: string; id?: string; item_id?: string | null; reference_label?: string | null; role: string; shared_reference?: boolean }, { attachment_id?: string; created_at?: string; demand_id?: string; id?: string; item_id?: string | null; reference_label?: string | null; role?: string; shared_reference?: boolean }, [Rel<"adjustment_item_attachments_attachment_id_fkey", ["attachment_id"], "adjustment_attachments">, Rel<"adjustment_item_attachments_demand_id_fkey", ["demand_id"], "adjustment_demands">, Rel<"adjustment_item_attachments_item_id_fkey", ["item_id"], "adjustment_items">]>;
  adjustment_links: Table<{ created_at: string; demand_id: string; id: string; item_id: string | null; link_type: string; url: string }, { created_at?: string; demand_id: string; id?: string; item_id?: string | null; link_type?: string; url: string }, { created_at?: string; demand_id?: string; id?: string; item_id?: string | null; link_type?: string; url?: string }, [Rel<"adjustment_links_demand_id_fkey", ["demand_id"], "adjustment_demands">, Rel<"adjustment_links_item_id_fkey", ["item_id"], "adjustment_items">]>;
  adjustment_annotations: Table<{ created_at: string; highlight: string | null; id: string; item_id: string; semantic: string; span_index: number; text: string | null }, { created_at?: string; highlight?: string | null; id?: string; item_id: string; semantic: string; span_index: number; text?: string | null }, { created_at?: string; highlight?: string | null; id?: string; item_id?: string; semantic?: string; span_index?: number; text?: string | null }, [Rel<"adjustment_annotations_item_id_fkey", ["item_id"], "adjustment_items">]>;
}; Views: { [_ in never]: never }; Functions: { [_ in never]: never }; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };
export type Tables<Name extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][Name]["Row"];
export type TablesInsert<Name extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][Name]["Insert"];
export type TablesUpdate<Name extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][Name]["Update"];
